# Generated by Django 6.1.1 on 2026-09-09 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def validar_datos_previos(apps, schema_editor):
    alias = schema_editor.connection.alias
    Producto = apps.get_model('myapp', 'Producto')
    Venta = apps.get_model('myapp', 'Venta')
    productos = list(Producto.objects.using(alias).filter(models.Q(stock__lt=0) | models.Q(precio__lt=0)).values_list('pk', flat=True)[:20])
    ventas = list(Venta.objects.using(alias).filter(total__lt=0).values_list('pk', flat=True)[:20])
    if productos or ventas:
        raise RuntimeError(f'Datos negativos previos: productos {productos}, ventas {ventas}. Conciliar antes de migrar; no se modificó su valor.')


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validar_datos_previos, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='LOW_STOCK', max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNREAD', 'No leída'), ('READ', 'Leída')], default='UNREAD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ItemReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('restore_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INITIAL', 'Inicial'), ('RESTOCK', 'Reabastecimiento'), ('SALE', 'Venta'), ('REFUND', 'Reembolso'), ('ADJUSTMENT_IN', 'Ajuste de entrada'), ('ADJUSTMENT_OUT', 'Ajuste de salida')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('SELLER', 'Vendedor')], default='SELLER', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='producto',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='producto',
            name='min_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='venta',
            name='receipt_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('PARTIALLY_REFUNDED', 'Parcialmente reembolsada'), ('REFUNDED', 'Reembolsada')], default='DRAFT', max_length=25),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='venta_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='venta_descuento_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('tax__gte', 0)), name='venta_impuesto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='venta_total_no_negativo'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='myapp.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='myapp.categoria'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='producto_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='producto_costo_no_negativo'),
        ),
        migrations.AddField(
            model_name='itemreembolso',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_reembolso', to='myapp.producto'),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_venta', to='myapp.producto'),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.venta'),
        ),
        migrations.AddField(
            model_name='itemreembolso',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_reembolso', to='myapp.itemventa'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='myapp.producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='myapp.venta'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to='myapp.venta'),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='myapp.reembolso'),
        ),
        migrations.AddField(
            model_name='itemreembolso',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.reembolso'),
        ),
        migrations.AddConstraint(
            model_name='itemventa',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='item_venta_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemventa',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='item_venta_descuento_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itemventa',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='producto_unico_por_venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='movimiento_cantidad_no_cero'),
        ),
        migrations.AddConstraint(
            model_name='itemreembolso',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reembolso_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemreembolso',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='reembolso_importe_no_negativo'),
        ),
    ]
