# Generated by Django 6.1.1 on 2026-09-09 22:21

import django.db.models.deletion
import django.db.models.expressions
import myapp.models
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


def comprobar_historial(apps, schema_editor):
    alias = schema_editor.connection.alias
    # También cubre instalaciones que ya ejecutaron la versión anterior de 0005.
    import_module('myapp.migrations.0005_identificadores_requeridos').completar_datos_existentes(apps, schema_editor)
    Venta = apps.get_model('myapp', 'Venta')
    antiguas = Venta.objects.using(alias).filter(items__isnull=True).filter(
        models.Q(status__in=['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED']) |
        models.Q(status='DRAFT', receipt_number__startswith='LEGACY-'))
    for venta in antiguas:
        venta.legacy = True
        if venta.status == 'DRAFT':
            venta.status = 'COMPLETED'
            venta.completed_at = venta.created_at
            venta.subtotal = venta.total
        venta.save(using=alias)
    Reembolso = apps.get_model('myapp', 'Reembolso')
    # La implementación previa no guardaba la fecha real ni calculaba importes.
    # No inventar datos contables para aplicar una restricción nueva.
    pendientes = list(Reembolso.objects.using(alias).filter(status='COMPLETED', completed_at__isnull=True).values_list('pk', flat=True)[:20])
    if pendientes:
        raise RuntimeError(f'Reembolsos previos {pendientes}: conciliar importes, bases y fechas antes de aplicar 0006.')
    Alerta = apps.get_model('myapp', 'Alerta')
    vistos = set()
    for alerta in Alerta.objects.using(alias).filter(status='UNREAD', product__isnull=False).order_by('-pk'):
        clave = (alerta.product_id, alerta.type)
        if clave in vistos:
            alerta.status = 'READ'
            alerta.read_at = alerta.created_at
            alerta.save(using=alias, update_fields=['status', 'read_at'])
        vistos.add(clave)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_identificadores_requeridos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name='venta', name='legacy', field=models.BooleanField(default=False, editable=False)),
        migrations.AddField(
            model_name='itemreembolso',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(comprobar_historial, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='itemreembolso',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemreembolso',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='myapp.reembolso'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='myapp.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='receipt_number',
            field=models.CharField(default=myapp.models.numero_comprobante, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'UNREAD')), fields=('product', 'type'), name='alerta_abierta_unica'),
        ),
        migrations.AddConstraint(
            model_name='itemreembolso',
            constraint=models.UniqueConstraint(fields=('refund', 'sale_item'), name='detalle_unico_por_reembolso'),
        ),
        migrations.AddConstraint(
            model_name='itemreembolso',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gte', 0)), name='refund_base_valida'),
        ),
        migrations.AddConstraint(
            model_name='itemventa',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('subtotal__gte', 0)), name='item_venta_valores_validos'),
        ),
        migrations.AddConstraint(
            model_name='itemventa',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='item_venta_costo_valido'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('new_stock', django.db.models.expressions.CombinedExpression(models.F('previous_stock'), '+', models.F('quantity')))), name='movimiento_balance_valido'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['SALE', 'ADJUSTMENT_OUT']), ('quantity__lt', 0)), models.Q(('movement_type__in', ['INITIAL', 'RESTOCK', 'REFUND', 'ADJUSTMENT_IN']), ('quantity__gt', 0)), _connector='OR'), name='movimiento_signo_valido'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'SALE'), ('refund__isnull', True), ('sale__isnull', False)), models.Q(('movement_type', 'REFUND'), ('refund__isnull', False), ('sale__isnull', False)), models.Q(('movement_type__in', ['INITIAL', 'RESTOCK', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT']), ('refund__isnull', True), ('sale__isnull', True)), _connector='OR'), name='movimiento_referencia_valida'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('sku', ''), _negated=True), name='producto_sku_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='reembolso',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='refund_total_valido'),
        ),
        migrations.AddConstraint(
            model_name='reembolso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status__in', ['PENDING', 'CANCELLED'])), models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), _connector='OR'), name='refund_estado_fecha_valida'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('receipt_number', ''), _negated=True), name='venta_comprobante_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'COMPLETED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED'])), name='venta_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status__in', ['DRAFT', 'CANCELLED'])), models.Q(('completed_at__isnull', False), ('status__in', ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'])), _connector='OR'), name='venta_fecha_coherente'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__isnull', True), ('amount_received__gte', 0), _connector='OR'), name='venta_recibido_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('change_amount__isnull', True), ('change_amount__gte', 0), _connector='OR'), name='venta_cambio_no_negativo'),
        ),
    ]
