# Generated by Django 6.1.1 on 2026-09-09 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auditoria_integridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('movement_type', 'SALE')), fields=('sale', 'product'), name='movimiento_venta_unico'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('movement_type', 'REFUND')), fields=('refund', 'product'), name='movimiento_reembolso_unico'),
        ),
    ]
